# Generated by Django 4.1 on 2023-01-25 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_date", models.DateField()),
                ("end_time", models.TimeField()),
                ("cat", models.CharField(max_length=10)),
                ("phone_number", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "number_room",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("bookings", models.ManyToManyField(to="cat_hotel.booking")),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cat_hotel.room"
            ),
        ),
    ]
