# Generated by Django 4.1 on 2023-01-25 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="bookings",),
        migrations.AddField(
            model_name="booking",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cat_hotel.customer",
            ),
        ),
    ]
