# Generated by Django 4.1 on 2023-01-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel", "0002_remove_customer_bookings_booking_customer"),
    ]

    operations = []
