# Generated by Django 4.1 on 2023-01-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel", "0003_auto_20230126_0239"),
    ]

    operations = []
