# Generated by Django 4.1 on 2023-01-25 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel", "0004_auto_20230126_0240"),
    ]

    operations = []
